version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/prodapp

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 3000
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 3000
      runas: ubuntu
  