version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/prodapp

hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
  
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: ubuntu
  