version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing Python dependencies...
      - sudo apt update
      - sudo apt install python3 python3-pip -y
      - pip install --upgrade pip

  pre_build:
    commands:
      - echo Running pre-build steps...
      - aws codeartifact login --tool pip --repository devops_artifact --domain devops --domain-owner 624564777830 --region eu-north-1
      - echo Pre-build steps completed.
  build:
    commands:
      - echo Build started on `date`
      - pip install -r requirements.txt 
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Post-build steps...
      - zip -r app.zip . -x "venv/*" "*.pyc" "__pycache__/*" ".git/*"
      - echo Post-build steps completed.

artifacts:
  files:
    - '**/*'

